/**
 * One-time seed script: migrates hardcoded HTML data into SQLite.
 * Run: cd server && node db/seed.js
 */
const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs');
const config = require('../config');
const { init } = require('./database');

// ─── People data (extracted from people.html) ───
const people = [
  // FACULTY
  { name: 'Juanzi Li', title: 'Professor', role: 'faculty', photo: 'faculty/juanzi.png', photo_position: '50% 0%', link: 'https://keg.cs.tsinghua.edu.cn/persons/ljz/', supervisor: null, email: null, bio: null, year_start: null, year_end: null, sort_order: 1 },
  { name: 'Jie Tang', title: 'Professor', role: 'faculty', photo: 'faculty/jie.png', photo_position: '50% 90%', link: 'https://keg.cs.tsinghua.edu.cn/jietang/', supervisor: null, email: null, bio: null, year_start: null, year_end: null, sort_order: 2 },
  { name: 'Bin Xu', title: 'Professor', role: 'faculty', photo: 'faculty/bin.png', photo_position: null, link: 'https://keg.cs.tsinghua.edu.cn/persons/xubin/', supervisor: null, email: null, bio: null, year_start: null, year_end: null, sort_order: 3 },
  { name: 'Yuxiao Dong', title: 'Associate Professor', role: 'faculty', photo: 'faculty/yuxiao.png', photo_position: '50% 60%', link: 'https://keg.cs.tsinghua.edu.cn/yuxiao/', supervisor: null, email: null, bio: null, year_start: null, year_end: null, sort_order: 4 },
  { name: 'Lei Hou', title: 'Associate Professor', role: 'faculty', photo: 'faculty/lei.png', photo_position: '20% 20%', link: null, supervisor: null, email: null, bio: null, year_start: null, year_end: null, sort_order: 5 },

  // PHD STUDENTS
  { name: 'Mengyang Sun', title: 'PhD, 2019 - Present', role: 'phd', photo: 'people/mengyang.png', photo_position: '50% 30%', link: 'https://openreview.net/profile?id=~Mengyang_Sun3', supervisor: 'Jie Tang', email: 'sunmy19@mails.tsinghua.edu.cn', bio: 'Mengyang Sun is a Ph.D student at Tsinghua University, supervised by Prof. Jie Tang. His research interest lies in multilingual models, multi-task learning, and parameter-efficient fine-tuning of LLMs. He has published papers at conferences such as ICML, CIKM and WWW.', year_start: 2019, year_end: null, sort_order: 1 },
  { name: 'Zhenyu Hou', title: 'PhD, 2021 - Present', role: 'phd', photo: 'people/zhenyu.jpg', photo_position: null, link: 'https://think2try.github.io/', supervisor: 'Yuxiao Dong', email: 'zhenyu.hou08@gmail.com', bio: "Zhenyu Hou is a PhD student at Tsinghua University's KEG Lab, focusing on language model reasoning and reinforcement learning. He has published more than ten papers as a first author or co-first author at international conferences such as ICML, ACL, and KDD.", year_start: 2021, year_end: null, sort_order: 2 },
  { name: 'Xiao Liu', title: 'PhD, 2021 - Present', role: 'phd', photo: 'people/liuxiao.jpg', photo_position: null, link: 'https://github.com/xiao9905', supervisor: 'Jie Tang', email: 'shawliu9@gmail.com', bio: "Xiao Liu is a fifth-year PhD student in the Department of Computer Science at Tsinghua University. His primary research focuses on the algorithms and applications of foundation models and foundation agents.", year_start: 2021, year_end: null, sort_order: 3 },
  { name: 'Jinhua Du', title: 'PhD, 2022 - Present', role: 'phd', photo: 'people/jinhua.png', photo_position: '50% 10%', link: 'https://dujh22.github.io/Dujinhua_wiki/', supervisor: 'Jie Tang', email: 'dujh22@mails.tsinghua.edu.cn', bio: 'Jinhua Du is a PhD student in the Department of Computer Science and Technology at Tsinghua University. He works on large language models, focusing on logical reasoning, reliability, and agentic systems for scalable evaluation and training.', year_start: 2022, year_end: null, sort_order: 4 },
  { name: 'Wenyi Hong', title: 'PhD, 2022 - Present', role: 'phd', photo: 'people/wenyi.png', photo_position: '50% 100%', link: 'https://wenyihong.github.io/', supervisor: 'Jie Tang', email: 'wenyi.hong@outlook.com', bio: 'Wenyi Hong is a PhD student in the Department of Computer Science and Technology at Tsinghua University. Her research interest mainly focuses on multimodal foundation models, including vision-language models, multimodal agents, and vision generation models.', year_start: 2022, year_end: null, sort_order: 5 },
  { name: 'Jiazheng Xu', title: 'PhD, 2022 - Present', role: 'phd', photo: 'people/jiazheng.png', photo_position: null, link: 'https://github.com/xujz18', supervisor: 'Yuxiao Dong', email: 'xujz0703@gmail.com', bio: 'Jiazheng Xu is a PhD student in the Department of Computer Science and Technology at Tsinghua University. His research interest mainly focuses on multimodal generative models, including reinforcement learning, evaluation and alignment.', year_start: 2022, year_end: null, sort_order: 6 },
  { name: 'Zhuoyi Yang', title: 'PhD, 2022 - Present', role: 'phd', photo: 'people/zhuoyi.png', photo_position: '50% 0%', link: 'https://yzy-thu.github.io/zhuoyiyang.github.io/', supervisor: 'Jie Tang', email: 'zhuoyiyang2000@gmail.com', bio: 'Zhuoyi Yang is a PhD Candidate at Tsinghua University, with research interests both in multimodal generation and understanding. His work focuses on text-to-image/video generation, and visual understanding.', year_start: 2022, year_end: null, sort_order: 7 },
  { name: 'Aohan Zeng', title: 'PhD, 2022 - Present', role: 'phd', photo: 'people/aohan.jpg', photo_position: null, link: 'https://github.com/Sengxian', supervisor: 'Jie Tang', email: 'sengxian@live.com', bio: 'Aohan Zeng is a PhD student in the Department of Computer Science and Technology at Tsinghua University. His research interest mainly focuses on large language models, including pre-training, efficient architecture and coding agents.', year_start: 2022, year_end: null, sort_order: 8 },
  { name: 'Xiao Xia', title: 'PhD, 2023 - Present', role: 'phd', photo: 'people/xiaxiao.png', photo_position: null, link: 'https://github.com/Rishubi', supervisor: 'Yuxiao Dong', email: 'xiax23@mails.tsinghua.edu.cn', bio: 'Xiao Xia is a PhD student in the Department of Computer Science and Technology at Tsinghua University. His research interest mainly focuses on code generation and agents.', year_start: 2023, year_end: null, sort_order: 9 },
  { name: 'Yifan Xu', title: 'PhD, 2023 - Present', role: 'phd', photo: 'people/xuyifan.png', photo_position: null, link: 'https://github.com/xuyifan-0731', supervisor: 'Yuxiao Dong', email: 'xuyifan2001@gmail.com', bio: 'Yifan Xu is a PhD student in the Department of Computer Science at Tsinghua University. His research interest mainly focuses on mobile GUI agents, including reinforcement learning for agent training, multimodal models, and agent evaluation and benchmarking.', year_start: 2023, year_end: null, sort_order: 10 },
  { name: 'Qinkai Zheng', title: 'PhD, 2023 - Present', role: 'phd', photo: 'people/qinkai.png', photo_position: null, link: 'https://github.com/Stanislas0', supervisor: 'Jie Tang', email: 'zqk23@mails.tsinghua.edu.cn', bio: 'Qinkai Zheng is a Ph.D. student in the Department of Computer Science at Tsinghua University. His research focuses on code generation model and coding agent.', year_start: 2023, year_end: null, sort_order: 11 },
  { name: 'Wendi Zheng', title: 'PhD, 2023 - Present', role: 'phd', photo: 'people/wendi.png', photo_position: null, link: 'https://scholar.google.com/citations?user=6v5wcQ8AAAAJ&hl=en', supervisor: 'Jie Tang', email: 'zhengwd23@mails.tsinghua.edu.cn', bio: 'Wendi Zheng is a Ph.D. student in the Department of Computer Science at Tsinghua University. His research interests mainly focus on visual generative models, for example text-to-image generation.', year_start: 2023, year_end: null, sort_order: 12 },
  { name: 'Mingdao Liu', title: 'PhD, 2024 - Present', role: 'phd', photo: 'people/mingdao.png', photo_position: null, link: 'https://github.com/Btlmd', supervisor: 'Yuxiao Dong', email: 'liumd24@mails.tsighua.edu.cn', bio: 'Mingdao Liu is a PhD student in the Department of Computer Science and Technology at Tsinghua University. His research interests mainly focus on large language model pre-training and agentic coding.', year_start: 2024, year_end: null, sort_order: 13 },
  { name: 'Jiayan Teng', title: 'PhD, 2024 - Present', role: 'phd', photo: 'people/jiayan.png', photo_position: null, link: 'https://tengjiayan20.github.io/', supervisor: 'Jie Tang & Xuelong Li (TeleAI)', email: 'tengjy24@mails.tsinghua.edu.cn', bio: 'Jiayan Teng is a PhD student in the Department of Computer Science and Technology at Tsinghua University. His research interest mainly focuses on image generation, video generation and diffusion models.', year_start: 2024, year_end: null, sort_order: 14 },
  { name: 'Hanyu Lai', title: 'PhD, 2025 - Present', role: 'phd', photo: 'people/hanyu.png', photo_position: '50% 30%', link: 'https://scholar.google.com.hk/citations?user=cuFVHjwAAAAJ&hl=fr', supervisor: 'Jie Tang', email: 'laihy25@mails.tsinghua.edu.cn', bio: 'Hanyu Lai is a PhD student in the Department of Computer Science and Technology at Tsinghua University. His research interest mainly focuses on GUI Agent, Post-Training and Agentic RL.', year_start: 2025, year_end: null, sort_order: 15 },
  { name: 'Wenkai Li', title: 'PhD, 2025 - Present', role: 'phd', photo: 'people/wenkai.png', photo_position: null, link: null, supervisor: 'Jie Tang & Xuelong Li (TeleAI)', email: 'lwk21@mails.tsinghua.edu.cn', bio: 'Wenkai Li is a PhD student in the Department of Computer Science and Technology at Tsinghua University. His research interest mainly focuses on GUI Agent.', year_start: 2025, year_end: null, sort_order: 16 },
  { name: 'Yujiang Li', title: 'PhD, 2025 - Present', role: 'phd', photo: 'people/yujiang.png', photo_position: null, link: 'https://scholar.google.com/citations?user=p9VZOkIAAAAJ', supervisor: 'Yuxiao Dong', email: 'liyujiang2020@gmail.com', bio: 'Yujiang Li is a PhD student in College AI at Tsinghua University. Her research interest mainly focuses on language model reasoning, machine learning agent and reinforcement learning.', year_start: 2025, year_end: null, sort_order: 17 },
  { name: 'Rui Lu', title: 'PhD, 2025 - Present', role: 'phd', photo: 'people/lurui.png', photo_position: null, link: 'https://learningrate1.com/', supervisor: 'Yuxiao Dong', email: 'lu-r21@mails.tsinghua.edu.cn', bio: 'Rui Lu is a PhD student in the Department of Computer Science and Technology at Tsinghua University. His research focuses on LLM, Agentic RL and Deep Research Agent.', year_start: 2025, year_end: null, sort_order: 18 },
  { name: 'Bowen Lv', title: 'PhD, 2025 - Present', role: 'phd', photo: 'people/bowen.png', photo_position: '50% 0%', link: 'https://extreme1228.github.io/extreme1228/', supervisor: 'Yuxiao Dong', email: 'lvbw25@mail.tsinghua.edu.cn', bio: 'Bowen Lv is a PhD student in the Department of Computer Science and Technology at Tsinghua University. His research interest mainly focuses on LLM, Agentic RL and GUI Agent.', year_start: 2025, year_end: null, sort_order: 19 },
  { name: 'Xixuan Song', title: 'PhD, 2025 - Present', role: 'phd', photo: 'people/xixuan.png', photo_position: null, link: 'https://github.com/songxxzp/', supervisor: 'Ling Feng & Jie Tang', email: 'songxx21@mails.tsinghua.edu.cn', bio: 'Song Xixuan is a PhD student in the Department of Computer Science and Technology at Tsinghua University. His research interest mainly focuses on MultiModal and Agentic RL.', year_start: 2025, year_end: null, sort_order: 20 },
  { name: 'Daniel Zhang', title: 'PhD, 2025 - Present', role: 'phd', photo: 'people/shudan.png', photo_position: '50% 60%', link: 'https://scholar.google.com/citations?user=Z-SskNIAAAAJ&hl=en&oi=ao', supervisor: 'Jie Tang', email: 'zhangsd25@mails.tsinghua.edu.cn', bio: 'Shudan Zhang is a PhD student in the Department of Computer Science and Technology at Tsinghua University. His research interest mainly focuses on GUI Agent, Agentic RL and Post-Training.', year_start: 2025, year_end: null, sort_order: 22 },

  // MASTER STUDENTS
  { name: 'Zeyi Chen', title: 'Master, 2023 - Present', role: 'master', photo: 'people/zeyi.png', photo_position: '50% 60%', link: 'https://www.linkedin.com/in/zeyi-chen-a429a2218/', supervisor: 'Jie Tang', email: 'chenzy23@mails.tsinghua.edu.cn', bio: 'Zeyi Chen is a Master student in the Global Innovation Exchange at Tsinghua University, supervised by Jie Tang. His research interests mainly focuses on LLM Post-Training, especially Sample Efficiency and Test-Time Training.', year_start: 2023, year_end: null, sort_order: 1 },
  { name: 'Xinghan Liu', title: 'Master, 2023 - Present', role: 'master', photo: 'people/xinghan.png', photo_position: null, link: 'https://scholar.google.com/citations?hl=zh-CN&user=tu6FOA8AAAAJ', supervisor: null, email: 'xh-liu23@mails.tsinghua.edu.cn', bio: 'Xinghan Liu is a Master student at Tsinghua University, supervised by Prof. Jie Tang. His research interest mainly focuses on developing GUI Agents through Post-Training methods.', year_start: 2023, year_end: null, sort_order: 2 },
  { name: 'Matthew Taruno', title: 'Master, 2023 - Present', role: 'master', photo: 'people/jiahui.png', photo_position: '50% 90%', link: 'https://www.linkedin.com/in/mtaruno', supervisor: 'Jie Tang', email: 'matthew.taruno@gmail.com', bio: 'Matthew Taruno is a Master student in the Global Innovation Exchange at Tsinghua University, supervised by Jie Tang. His research interests mainly focuses on Post-Training, Reinforcement Learning, and Generalizable Agentic Systems.', year_start: 2023, year_end: null, sort_order: 3 },
  { name: 'Yuzhe Zhang', title: 'Master, 2023 - Present', role: 'master', photo: 'people/yuzhe.png', photo_position: null, link: 'https://zyzzzz-123.github.io/', supervisor: 'Jie Tang', email: 'frankyuzhe@gmail.com', bio: 'Yuzhe Zhang is a Master student in the Global Innovation Exchange at Tsinghua University, supervised by Jie Tang. His research interests mainly focuses on Post-Training, Coding Agent, Benchmarking and Evaluation.', year_start: 2023, year_end: null, sort_order: 4 },
  { name: 'Iat Long Iong', title: 'Master, 2024 - Present', role: 'master', photo: 'people/yilang.png', photo_position: null, link: 'https://github.com/boxworld18', supervisor: 'Jie Tang', email: 'iong.iatlong@gmail.com', bio: 'Iat Long Iong is a Master student in the Department of Computer Science and Technology at Tsinghua University. His research interests mainly focuses on GUI Agent, Agentic RL and Post-Training.', year_start: 2024, year_end: null, sort_order: 5 },
  { name: 'Zihan Wang', title: 'Master, 2024 - Present', role: 'master', photo: 'people/zihan.png', photo_position: null, link: 'https://pka.moe', supervisor: 'Jie Tang', email: 'w-zh24@mails.tsinghua.edu.cn', bio: 'Zihan Wang is a graduate student in the Department of Computer Science and Technology at Tsinghua University. His research interests mainly focus on large language models, including pre-training, algorithm design, and data attribution.', year_start: 2024, year_end: null, sort_order: 6 },
  { name: 'Alfonsus Rendy', title: 'Master, 2025 - Present', role: 'master', photo: 'people/xingguan.png', photo_position: null, link: 'https://rendyalfons.us/', supervisor: 'Yuxiao Dong', email: 'jixg25@mails.tsinghua.edu.cn', bio: "Alfonsus Rendy is a Master's student in the Advanced Computing Program at Tsinghua University. His research interests lie in foundation models for decision-making, with a focus on agentic systems, reinforcement learning for agent training, and the development of self-improving and open-ended agents.", year_start: 2025, year_end: null, sort_order: 7 },
  { name: 'Xirui Pan', title: 'Master, 2025 - Present', role: 'master', photo: 'people/xirui.png', photo_position: '50% 0%', link: null, supervisor: 'Jie Tang', email: 'panxr25@mails.tsinghua.edu.cn', bio: "Xirui Pan is a Master's student in the Department of Computer Science and Technology at Tsinghua University, supervised by Prof. Jie Tang. His research interests primarily focus on Large Language Models (LLMs) and Model Evaluation and Benchmarking.", year_start: 2025, year_end: null, sort_order: 8 },
  { name: 'Wenhao Yan', title: 'Master, 2025 - Present', role: 'master', photo: 'people/wenhao.png', photo_position: '50% 90%', link: null, supervisor: 'Jie Tang', email: 'wh-yan25@mails.tsinghua.edu.cn', bio: "Wenhao Yan is a Master's student in GIX program at Tsinghua University, supervised by Prof. Jie Tang. His research interests primarily focus on Diffusion Models and Video Generation with Multi-modal Conditions.", year_start: 2025, year_end: null, sort_order: 9 },
  { name: 'Shuntian Yao', title: 'Master, 2025 - Present', role: 'master', photo: 'people/shuntian.png', photo_position: null, link: null, supervisor: 'Jie Tang', email: 'yst25@mails.tsinghua.edu.cn', bio: "Shuntian Yao is a Master's student in GIX program at Tsinghua University, supervised by Prof. Jie Tang. His research interests primarily focus on Reinforcement Learning Algorithms and LLM Agents.", year_start: 2025, year_end: null, sort_order: 10 },
  { name: 'Sining Zhoubian', title: 'Master, 2025 - Present', role: 'master', photo: 'people/sining.png', photo_position: null, link: 'https://github.com/zhoubiansining', supervisor: 'Jie Tang', email: 'zbsn21@mails.tsinghua.edu.cn', bio: 'Sining Zhoubian is a Master student in the Department of Computer Science and Technology at Tsinghua University. His research interest mainly focuses on large language models, including advanced reasoning, reinforcement learning paradigms, self improvement algorithms and agents.', year_start: 2025, year_end: null, sort_order: 11 },

  // UNDERGRADUATE STUDENTS
  { name: 'Zehai He', title: 'Undergraduate, 2022 - Present', role: 'undergraduate', photo: 'people/zehai.png', photo_position: null, link: 'https://he-zh22.github.io/', supervisor: 'Jie Tang', email: 'he-zh22@mails.tsinghua.edu.cn', bio: 'Zehai He is a senior undergraduate student in the Department of Computer Science and Technology at Tsinghua University. His research interests mainly focus on multimodal large language models, multimodal agents.', year_start: 2022, year_end: null, sort_order: 1 },
  { name: 'Zhiyuan Liao', title: 'Undergraduate, 2022 - Present', role: 'undergraduate', photo: 'people/zhiyuan.png', photo_position: null, link: 'https://github.com/intkun', supervisor: 'Yuxiao Dong', email: 'liao-zy22@mails.tsinghua.edu.cn', bio: 'Zhiyuan Liao is a senior undergraduate in the Department of Computer Science and Technology at Tsinghua University. His research interests mainly focus on LLM post-training and multimodal generative models.', year_start: 2022, year_end: null, sort_order: 2 },
  { name: 'Keyun Luo', title: 'Undergraduate, 2022 - Present', role: 'undergraduate', photo: 'people/keyun.png', photo_position: null, link: 'https://github.com/as-lky/', supervisor: 'Jie Tang', email: 'luoky22@mails.tsinghua.edu.cn', bio: 'Keyun Luo is a senior undergraduate student in the Zhili College at Tsinghua University. His research interests mainly focus on large language models and AI agents.', year_start: 2022, year_end: null, sort_order: 3 },
  { name: 'Xueqiao Sun', title: 'Undergraduate, 2022 - Present', role: 'undergraduate', photo: 'people/xueqiao.png', photo_position: '50% 0%', link: 'https://huggingface.co/snow1007', supervisor: 'Jie Tang & Shuo Liu', email: 'snow10072740@gmail.com', bio: 'Xueqiao Sun is an undergraduate student double majoring in Computer Science and Finance at Tsinghua University. Her research interest mainly focuses on AI Agents and Reinforcement Learning.', year_start: 2022, year_end: null, sort_order: 4 },
  { name: 'Haoran Wang', title: 'Undergraduate, 2022 - Present', role: 'undergraduate', photo: 'people/haoran.png', photo_position: '50% 80%', link: 'https://github.com/UbeCc', supervisor: 'Yuxiao Dong', email: 'ubecwang@gmail.com', bio: 'Haoran Wang is a senior undergraduate in the Department of Computer Science and Technology at Tsinghua University. His research interests mainly focus on LLM post-training and coding agents.', year_start: 2022, year_end: null, sort_order: 5 },
  { name: 'Hanchen Zhang', title: 'Undergraduate, 2022 - Present', role: 'undergraduate', photo: 'people/haochen.png', photo_position: '50% 80%', link: 'https://github.com/zhc7', supervisor: 'Yuxiao Dong', email: 'zhanghanchen77@gmail.com', bio: 'Hanchen Zhang is a senior undergraduate in the Department of Computer Science and Technology at Tsinghua University. His research interests mainly focus on LLM post-training and agents.', year_start: 2022, year_end: null, sort_order: 6 },

  // POSTDOCTORAL RESEARCHERS
  { name: 'Shicheng Tan', title: 'Postdoc, 2024 - Present', role: 'postdoc', photo: 'people/shicheng.png', photo_position: '50% 0%', link: 'https://github.com/aitsc', supervisor: 'Jie Tang', email: 'tsctan@foxmail.com', bio: 'Shicheng Tan is a postdoctoral researcher at the Department of Computer Science and Technology, Tsinghua University. His research focuses on AI for Education, particularly on building intelligent teaching assistant systems powered by large language models.', year_start: 2024, year_end: null, sort_order: 1 },
  { name: 'Huanjing Zhao', title: 'Postdoc, 2024 - Present', role: 'postdoc', photo: 'people/huanjing.png', photo_position: null, link: 'https://github.com/hwangyeong', supervisor: 'Jie Tang', email: 'huanjingzhj@foxmail.com', bio: 'Huanjing Zhao is a Postdoctoral Researcher in the Department of Computer Science and Technology at Tsinghua University. His current research interests focus on personalized test item generation leveraging Large Language Models (LLMs).', year_start: 2024, year_end: null, sort_order: 2 },
  { name: 'Cunxiang Wang', title: 'Postdoc, 2024 - Present@Z.ai', role: 'postdoc', photo: 'people/cunxiang.png', photo_position: '50% -10%', link: 'https://wangcunxiang.github.io/', supervisor: 'Jie Tang', email: 'wangcunxiang303@gmail.com', bio: 'Cunxiang Wang is currently a postdoctoral researcher in the Department of Computer Science and Technology at Tsinghua University as well as a researcher at ZhipuAI, working with Prof. Jie Tang. He is now working on Agentic Coding, General Agents and LLM Evaluation.', year_start: 2024, year_end: null, sort_order: 3 },
  { name: 'Tong Yang', title: 'Postdoc, 2024 - Present@Z.ai', role: 'postdoc', photo: 'people/tong.png', photo_position: '50% 80%', link: 'https://zjutongyang.github.io/', supervisor: 'Jie Tang', email: 'yangtong@tsinghua.edu.cn', bio: 'Tong Yang is currently a postdoctoral researcher in the Department of Computer Science and Technology at Tsinghua University. His research interests span across embodied intelligence and planning problems for complex robotic systems.', year_start: 2024, year_end: null, sort_order: 4 },
  { name: 'Zhen Yang', title: 'Postdoc, 2025 - Present', role: 'postdoc', photo: 'people/zhen.png', photo_position: '50% 0%', link: 'https://zyang-16.github.io/zhenyang.github.io/', supervisor: 'Jie Tang', email: 'yang-zhen@mail.tsinghua.edu.cn', bio: 'Zhen Yang is a postdoctoral researcher in the Department of Computer Science and Technology at Tsinghua University. Her research interests include vision-language models, large language models, and graph representation learning.', year_start: 2025, year_end: null, sort_order: 5 },
  { name: 'Yi Zhao', title: 'Postdoc, 2025 - Present', role: 'postdoc', photo: 'people/zhaoyi.png', photo_position: '50% 90%', link: 'https://scholar.google.co.jp/citations?user=7Asw0ZkAAAAJ&hl=zh-CN&oi=sra', supervisor: 'Jie Tang', email: 'zhaoyi.hb@gmail.com', bio: 'Yi Zhao is currently a Postdoctoral Researcher at Tsinghua University. His current research interests focus on multimodal systems and data mining.', year_start: 2025, year_end: null, sort_order: 6 },
  { name: 'Ji Qi', title: 'Postdoc, 2025 - Present@Z.ai', role: 'postdoc', photo: 'people/jiqi.png', photo_position: '50% 0%', link: 'https://scholar.google.com/citations?user=vv6bZjMAAAAJ&hl', supervisor: 'Jie Tang', email: 'qijithu@gmail.com', bio: 'Ji Qi is a Postdoctoral Researcher jointly affiliated with Tsinghua University and Zhipu AI. His current research interests focus on the development of multimodal large language models.', year_start: 2025, year_end: null, sort_order: 7 },
  { name: 'Liying Tao', title: 'Postdoc, 2025 - Present', role: 'postdoc', photo: 'people/liying.png', photo_position: null, link: null, supervisor: 'Jie Tang', email: 'taoly@mail.tsinghua.edu.cn', bio: 'Liying Tao is a Postdoctoral Researcher in the Department of Computer Science and Technology at Tsinghua University. Her current research interests lie in the evaluation of Large Language Models (LLMs).', year_start: 2025, year_end: null, sort_order: 8 },
  { name: 'Xin Miao', title: 'Postdoc, 2025 - Present', role: 'postdoc', photo: 'people/miaoxin.png', photo_position: '50% 0%', link: 'https://scholar.google.com/citations?hl=zh-CN&user=IOFX_FgAAAAJ&view_op=list_works&authuser=1', supervisor: 'Jie Tang', email: 'miaox1994@gmail.com', bio: "Xin Miao is a Postdoctoral Researcher in the Department of Computer Science and Technology at Tsinghua University. Her research lies at the intersection of psychology and human-AI interaction.", year_start: 2025, year_end: null, sort_order: 9 },

  // PART-TIME GRADUATE STUDENTS
  { name: 'Xu Cheng', title: 'Part-time, 2019 - Present', role: 'parttime', photo: 'people/chengxu.png', photo_position: null, link: null, supervisor: 'Jie Tang', email: 'chengx19@mails.tsinghua.edu.cn', bio: 'Xu Cheng is a PhD student in the Innovation Leadership Engineering Program at Tsinghua University and a technical committee member at Tencent.', year_start: 2019, year_end: null, sort_order: 1 },
  { name: 'Xingyu Yan', title: 'Part-time, 2022 - Present', role: 'parttime', photo: 'people/xingyu.png', photo_position: null, link: null, supervisor: 'Jie Tang', email: 'yxypriv@gmail.com', bio: 'Xingyu Yan is a PhD student in the Innovation Leadership Engineering Program at Tsinghua University and the Chief Architect at Zhipu AI.', year_start: 2022, year_end: null, sort_order: 2 },
  { name: 'Tao Liu', title: 'Part-time, 2024 - Present', role: 'parttime', photo: 'people/liutao.png', photo_position: null, link: null, supervisor: 'Jie Tang', email: 'liu-t24@mails.tsinghua.edu.cn', bio: 'Liu Tao is a PhD student in the Department of Computer Science at Tsinghua University, with main research interests including large models, agents, and reinforcement learning.', year_start: 2024, year_end: null, sort_order: 3 },
  { name: 'Xunkai Zhang', title: 'Part-time, 2025 - Present', role: 'parttime', photo: 'people/xunkai.png', photo_position: null, link: 'https://github.com/xunkai55', supervisor: 'Jie Tang', email: 'xunkai55@gmail.com', bio: 'Xunkai Zhang is a part-time PhD student in the Innovation Leadership Engineering Program at Tsinghua University, and the head of Edge AI Department at Z.ai.', year_start: 2025, year_end: null, sort_order: 4 },

  // VISITING STUDENTS
  { name: 'Yichen Xu', title: 'Undergraduate, 2021-present @Peking University', role: 'visiting', photo: 'people/yichen.png', photo_position: '50% 200%', link: 'https://www.yichenxu.com', supervisor: null, email: 'xuyc@stu.pku.edu.cn', bio: 'Yichen Xu is a senior undergraduate at Yuanpei College, Peking University and an incoming graduate student at Tsinghua University. His research interests lie in Agentic RL and Efficient Inference.', year_start: 2021, year_end: null, sort_order: 1 },
  { name: 'Yi Jing', title: 'Undergraduate, 2022-present @UESTC', role: 'visiting', photo: 'people/jingyi.png', photo_position: '50% 80%', link: null, supervisor: null, email: 'jingy200501@gmail.com', bio: 'Yi Jing is a senior undergraduate student at the School of Computer Science and Engineering, University of Electronic Science and Technology of China, and an incoming graduate student at Tsinghua University.', year_start: 2022, year_end: null, sort_order: 2 },
  { name: "Amine M'Charrak", title: 'PhD, 2021-present @University of Oxford', role: 'visiting', photo: 'people/.png', photo_position: null, link: null, supervisor: null, email: null, bio: null, year_start: 2021, year_end: null, sort_order: 3 },

  // ALUMNI
  { name: 'Tao Feng', title: 'Postdoc, 2024-2025', role: 'alumni', photo: 'people/fengtao.png', photo_position: null, link: 'https://hi-fengtao.github.io/', supervisor: 'Jie Tang', email: 'fengtao.hi@gmail.com', bio: 'Tao Feng was a Postdoctoral Researcher in the Department of Computer Science and Technology at Tsinghua University. His research interests include Video Generation, Vision-Language Model, GUI Agent and Continual Learning.', year_start: 2024, year_end: 2025, sort_order: 1 },
  { name: 'Fanjin Zhang', title: 'PhD, 2017-2023 & Postdoc, 2024-2025', role: 'alumni', photo: 'people/fanjin.png', photo_position: null, link: 'https://zfjsail.github.io/', supervisor: 'Jie Tang', email: 'fanjinz@ruc.edu.cn', bio: 'Fanjin Zhang is an Assistant Professor in the School of Information, Renmin University of China.', year_start: 2017, year_end: 2025, sort_order: 2 },
  { name: 'Zhengxiao Du', title: 'PhD, 2020-2025', role: 'alumni', photo: 'people/zhengxiao.png', photo_position: null, link: 'https://zxdu.xyz', supervisor: 'Jie Tang', email: null, bio: 'Zhengxiao Du is currently co-leading the base model group for GLM. He received a PhD in the Department of Computer Science and Technology at Tsinghua University in 2025, advised by Prof. Jie Tang.', year_start: 2020, year_end: 2025, sort_order: 3 },
  { name: 'Ming Zhou', title: 'PhD, 2019-2025', role: 'alumni', photo: 'people/zhouming.png', photo_position: '50% 0%', link: 'https://asjqmasjqm.github.io/', supervisor: 'Jie Tang', email: 'zhou-m19@tsinghua.org.cn', bio: 'Ming Zhou is currently an assistant researcher at the Institute of Computing Technology (ICT), Chinese Academy of Sciences.', year_start: 2019, year_end: 2025, sort_order: 4 },
  { name: 'Dan Zhang', title: 'PhD, 2021-2025', role: 'alumni', photo: 'people/zhangdan.png', photo_position: null, link: 'https://zhangdan0602.github.io/', supervisor: 'Jie Tang', email: 'zd18@tsinghua.org.cn', bio: 'Dan Zhang is a postdoc research fellow at the National University of Singapore, working with Prof. Chua Tat-Seng.', year_start: 2021, year_end: 2025, sort_order: 5 },
  { name: 'Bo Chen', title: 'PhD, 2021-2025', role: 'alumni', photo: 'people/chenbo.jpg', photo_position: '50% 0%', link: 'https://allanchen95.github.io/', supervisor: 'Jie Tang', email: 'allanchen224@gmail.com', bio: 'Chen Bo is a research scientist at ByteDance Seed, working on building intelligent AI agents.', year_start: 2021, year_end: 2025, sort_order: 6 },
  { name: 'Wei Wang', title: 'Postdoc, 2023-2025', role: 'alumni', photo: 'people/wangwei.png', photo_position: null, link: 'https://weiwangorg.github.io/', supervisor: 'Jie Tang', email: 'weiwangorg@163.com', bio: 'Wei Wang is an associate professor at Nankai University.', year_start: 2023, year_end: 2025, sort_order: 7 },
];

// ─── News articles (from news_events.html + index.html) ───
const articles = [
  { title: 'GLM-5: From Vibe Coding to Agentic Engineering', slug: 'glm-5-release', excerpt: 'We are proud to announce the release of GLM-5, targeting complex systems engineering and long-horizon agentic tasks.', content: '<p>We are proud to announce the release of GLM-5, targeting complex systems engineering and long-horizon agentic tasks.</p>', cover_image: 'news_sec/glm-5.png', category: 'research', type: 'news', published_at: '2026-02-12' },
  { title: 'GLM-4.7: Advancing the Coding Capability', slug: 'glm-4-7', excerpt: 'We introduce the GLM-4.7, your new coding partner, with Core Coding, Vibe Coding, Tool Using, and Complex Reasoning.', content: '<p>We introduce the GLM-4.7, your new coding partner, with Core Coding, Vibe Coding, Tool Using, and Complex Reasoning.</p>', cover_image: 'news_sec/glm-4.7.png', category: 'research', type: 'news', published_at: '2025-12-12', link: 'https://z.ai/blog/glm-4.7' },
  { title: 'GLM-4.6V: Open Source Multimodal Models with Native Tool Use', slug: 'glm-4-6v', excerpt: 'We officially introduce and open-source the GLM-4.6V series—our latest iteration in multimodal large language models.', content: '<p>We officially introduce and open-source the GLM-4.6V series—our latest iteration in multimodal large language models.</p>', cover_image: 'news_sec/glm-4.6v.png', category: 'research', type: 'news', published_at: '2025-12-08', link: 'https://z.ai/blog/glm-4.6v' },
  { title: 'AGI-Next Summit', slug: 'agi-next-summit', excerpt: 'The AGI-Next Summit is an invitation-only forum initiated by Tsinghua University, focusing on the key pathways of next-generation artificial general intelligence.', content: '<p>The AGI-Next Summit is an invitation-only forum initiated by Tsinghua University, focusing on the key pathways of next-generation artificial general intelligence and the role of open-source ecosystems in China.</p>', cover_image: 'news/agi-next-ok.png', category: 'community', type: 'news', published_at: '2026-01-12', link: 'https://kw.beijing.gov.cn/xwdt/bmdt/202601/t20260112_4424138.html' },
  { title: 'SIGKDD Test-of-Time Award', slug: 'sigkdd-test-of-time-award', excerpt: 'Our ArnetMiner paper received the ACM SIGKDD Test-of-Time Award for Applied Science, recognizing its long-term impact since 2008.', content: '<p>Our ArnetMiner paper received the ACM SIGKDD Test-of-Time Award for Applied Science, recognizing its long-term impact since 2008.</p>', cover_image: 'news/kdd-test-of-time-award-1.png', category: 'awards', type: 'news', published_at: '2025-08-01', link: 'https://www.tsinghua.edu.cn/info/1175/21357.htm' },
];

// ─── Events (from news_events.html) ───
const events = [
  { title: 'T²-Bench: Evaluating Conversational Agents in a Dual-Control Environment', description: '', speaker: 'Honghua Dong', location: 'Online', event_date: '2026-02-11 14:00:00', event_type: 'seminar', is_upcoming: 0 },
  { title: 'Test-Time Training', description: '', speaker: 'Yu Sun', location: 'Online (Zoom)', event_date: '2026-01-20 14:00:00', event_type: 'seminar', is_upcoming: 0 },
  { title: 'Titans + MIRAS: Helping AI Have Long-term Memory', description: '', speaker: 'Ali Behrouz', location: 'Online', event_date: '2026-01-12 14:00:00', event_type: 'seminar', is_upcoming: 0 },
];

// ─── Publications (extracted from publications.html) ───
const publications = [
  // Journal Publications — 2025
  { title: 'xTrimoPGLM: Unified 100B-Scale Pre-trained Transformer for Deciphering the Language of Protein', authors: 'Bo Chen, Xingyi Cheng, Pan Li, Yangli-ao Geng, Jing Gong, Shen Li, Zhilei Bei, Xu Tan, Boyan Wang, Xin Zeng, Chiming Liu, Aohan Zeng, Yuxiao Dong, Jie Tang, Le Song.', venue: 'Nature Methods 2025', year: 2025, category: 'journal', venue_tier: 'top-tier', pdf_url: 'https://www.nature.com/articles/s41592-025-02636-z', code_url: null, sort_order: 1 },
  { title: 'MCAP: Low-Pass GNNs with Matrix Completion for Academic Recommendations', authors: 'Dan Zhang, Shaojie Zheng, Yifan Zhu, Huihui Yuan, Jibing Gong, Jie Tang.', venue: 'ACM Transactions on Information Systems (TOIS), 2025', year: 2025, category: 'journal', venue_tier: 'top-tier', pdf_url: 'https://dl.acm.org/doi/10.1145/3698193', code_url: null, sort_order: 2 },
  { title: 'WebGLM: Towards An Efficient Web-Enhanced Question Answering System with Human Preferences', authors: 'Hanyu Lai, Xiao Liu, Hao Yu, Yifan Xu, Iat Long Iong, Shuntian Yao, Aohan Zeng, Zhengxiao Du, Yuxiao Dong and Jie Tang.', venue: 'ACM Transactions on Information Systems (TOIS), 2025', year: 2025, category: 'journal', venue_tier: 'top-tier', pdf_url: 'https://keg.cs.tsinghua.edu.cn/jietang/publications/KDD23-Liu-et-al-WebGLM.pdf', code_url: null, sort_order: 3 },
  { title: 'LGB: Language Model and Graph Neural Network-Driven Social Bot Detection', authors: 'Ming Zhou, Dan Zhang, Yuandong Wang, Yangli-ao Geng, Yuxiao Dong, and Jie Tang.', venue: 'IEEE Transaction on Knowledge and Data Engineering (TKDE), 2025', year: 2025, category: 'journal', venue_tier: 'top-tier', pdf_url: 'https://ieeexplore.ieee.org/document/11015729', code_url: null, sort_order: 4 },
  { title: 'Document-Level Relation Extraction With Low Entity Redundancy Feature Map', authors: 'Rongen Yan, Depeng Dang, Keqin Peng, Yakun Li, Ye Tao, Lei Hou, Juanzi Li and Jie Tang.', venue: 'IEEE Transaction on Knowledge and Data Engineering (TKDE), 2025', year: 2025, category: 'journal', venue_tier: 'top-tier', pdf_url: 'https://ieeexplore.ieee.org/document/11154073', code_url: null, sort_order: 5 },
  { title: 'ProtGO: universal protein function prediction utilizing multi-modal gene ontology knowledge', authors: 'Boyan Wang, Yangliao Geng, Xingyi Cheng, Bo Chen, Zhilei Bei, Wei Wang, Jie Tang, Le Song.', venue: 'Bioinformatics, 2025', year: 2025, category: 'journal', venue_tier: 'top-tier', pdf_url: 'https://pubmed.ncbi.nlm.nih.gov/40632605/', code_url: null, sort_order: 6 },
  { title: 'A Review of Generative Models for Virtual Human Motion Driving', authors: 'Pengcheng Wang, Haolun Peng, Siyang Mao, Shaojiang Wang, Jie Tang.', venue: 'Science China Information Sciences, 2025', year: 2025, category: 'journal', venue_tier: 'top-tier', pdf_url: 'https://link.springer.com/article/10.1007/s11432-023-4284-x', code_url: null, sort_order: 7 },
  { title: 'The Superalignment of Superhuman Intelligence with Large Language Models', authors: 'Minlie Huang, Yingkang Wang, Shiyao Cui, Pei Ke, Jie Tang.', venue: 'Science China Information Sciences, 2025', year: 2025, category: 'journal', venue_tier: 'top-tier', pdf_url: 'https://link.springer.com/article/10.1007/s11432-024-4348-6', code_url: null, sort_order: 8 },

  // Conference Publications — 2026
  { title: 'UDA: Unsupervised Debiasing Alignment for Pair-wise LLM-as-a-Judge', authors: 'Yang Zhang, Cunxiang Wang, Lindong Wu, Wenbo Yu, Yidong Wang, Guangsheng Bao, Jie Tang.', venue: "AAAI' 2026", year: 2026, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://arxiv.org/pdf/2508.09724', code_url: null, sort_order: 1 },
  { title: 'MathSE: Improving Multimodal Mathematical Reasoning via Self-Evolving Iterative Reflection and Reward-Guided Fine-Tuning', authors: 'Jinhao Chen, Zhen Yang, Jianxin Shi, Tianyu Wo, Jie Tang.', venue: "AAAI' 2026", year: 2026, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://arxiv.org/pdf/2511.06805', code_url: 'https://github.com/zheny2751-dotcom/MathSE', sort_order: 2 },
  { title: 'VisionReward: Fine-Grained Multi-Dimensional Human Preference Learning for Image and Video Generation', authors: 'Jiazheng Xu, Yu Huang, Jiale Cheng, Yuanming Yang, Jiajun Xu, Yuan Wang, Wenbo Duan, Shen Yang, Qunlin Jin, Shurun Li, Jiayan Teng, Zhuoyi Yang, Wendi Zheng, Xiao Liu, Dan Zhang, Ming Ding, Xiaohan Zhang, Shiyu Huang, Xiaotao Gu, Minlie Huang, Jie Tang, Yuxiao Dong.', venue: "AAAI' 2026", year: 2026, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://arxiv.org/pdf/2412.21059', code_url: 'https://github.com/zai-org/VisionReward', sort_order: 3 },

  // Conference Publications — 2025
  { title: 'GuARD: Effective Anomaly Detection through a Text-Rich and Graph Informed Language Model.', authors: 'Yunhe Pang, Bo Chen, Fanjin Zhang, Yanghui Rao, Evgeny Kharlamov, Jie Tang.', venue: "KDD' 2025", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://dl.acm.org/doi/10.1145/3711896.3736993', code_url: null, sort_order: 4 },
  { title: 'SoAy: A Solution-based LLM API-using Methodology for Academic Information Seeking', authors: 'Yuanchun Wang, Jifan Yu, Zijun Yao, Jing Zhang, Yuyang Xie, Shangqing Tu, Yiyang Fu, Youhe Feng, Jinkai Zhang, Jingyao Zhang, Bowen Huang, Yuanyao Li, Huihui Yuan, Lei Hou, Juanzi Li, Jie Tang.', venue: "KDD' 2025", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://dl.acm.org/doi/10.1145/3690624.3709412', code_url: null, sort_order: 5 },
  { title: 'MotionBench: Benchmarking and Improving Fine-grained Video Motion Understanding for Vision Language Models', authors: 'Wenyi Hong, Yean Cheng, Zhuoyi Yang, Weihan Wang, Lefan Wang, Xiaotao Gu, Shiyu Huang, Yuxiao Dong, Jie Tang.', venue: "CVPR' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://ieeexplore.ieee.org/document/11093895', code_url: null, sort_order: 6 },
  { title: 'AlignMMBench: Evaluating Chinese Multimodal Alignment in Large Vision-Language Models', authors: 'Yuhang Wu, Wenmeng Yu, Yean Cheng, Yan Wang, Xiaohan Zhang, Jiazheng Xu, Ming Ding, Yuxiao Dong.', venue: "ACL' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.acl-long.327/', code_url: null, sort_order: 7 },
  { title: 'TreeRL: LLM Reinforcement Learning with On-Policy Tree Search', authors: 'Zhenyu Hou, Ziniu Hu, Yujiang Li, Rui Lu, Jie Tang, Yuxiao Dong.', venue: "ACL' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.acl-long.604.pdf', code_url: null, sort_order: 8 },
  { title: 'AndroidGen: Building an Android Language Agent under Data Scarcity', authors: 'Hanyu Lai, Junjie Gao, Xiao Liu, Yifan Xu, Shudan Zhang, Yuxiao Dong, Jie Tang.', venue: "ACL' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.acl-long.138.pdf', code_url: null, sort_order: 9 },
  { title: 'AndroidLab: Training and Systematic Benchmarking of Android Autonomous Agents', authors: 'Yifan Xu, Xiao Liu, Xueqiao Sun, Siyi Cheng, Hao Yu, Hanyu Lai, Shudan Zhang, Dan Zhang, Jie Tang, and Yuxiao Dong.', venue: "ACL' 2025", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.acl-long.107/', code_url: null, sort_order: 10 },
  { title: 'SWE-Dev: Building Software Engineering Agents with Training and Inference Scaling Agents', authors: 'Haoran Wang, Zhenyu Hou, Yao Wei, Jie Tang, Yuxiao Dong.', venue: "ACL' 25 Findings", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.findings-acl.193.pdf', code_url: null, sort_order: 11 },
  { title: 'LongBench v2: Towards Deeper Understanding and Reasoning on Realistic Long-context Multitasks', authors: 'Yushi Bai, Shangqing Tu, Jiajie Zhang, Hao Peng, Xiaozhi Wang, Xin Lv, Shulin Cao, Jiazheng Xu, Lei Hou, Yuxiao Dong, Jie Tang, Juanzi Li.', venue: "ACL' 2025", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.acl-long.183/', code_url: null, sort_order: 12 },
  { title: 'A Survey of Post-Training Scaling in Large Language Models', authors: 'Hanyu Lai, Xiao Liu, Junjie Gao, Jiale Cheng, Zehan Qi, Yifan Xu, Shuntian Yao, Dan Zhang, Jinhua Du, Zhenyu Hou, Xin Lv, Minlie Huang, Yuxiao Dong, Jie Tang.', venue: "ACL' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.acl-long.140.pdf', code_url: null, sort_order: 13 },
  { title: 'CoT-based Synthesizer: Enhancing LLM Performance through Answer Synthesis', authors: 'Bohan Zhang, Xiaokang Zhang, Jing Zhang, Jifan Yu, Sijia Luo, Jie Tang.', venue: "ACL' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.acl-long.315/', code_url: null, sort_order: 14 },
  { title: 'Dynamic Scaling of Unit Tests for Code Reward Modeling', authors: 'Zeyao Ma, Xiaokang Zhang, Jing Zhang, Jifan Yu, Sijia Luo, Jie Tang.', venue: "ACL' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.acl-long.343.pdf', code_url: null, sort_order: 15 },
  { title: 'LongSafety: Evaluating Long-Context Safety of Large Language Models', authors: 'Yida Lu, Jiale Cheng, Zhexin Zhang, Shiyao Cui, Cunxiang Wang, Xiaotao Gu, Yuxiao Dong, Jie Tang, Hongning Wang, Minlie Huang.', venue: "ACL' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.acl-long.1530.pdf', code_url: null, sort_order: 16 },
  { title: 'LogicGame: Benchmarking Rule-Based Reasoning Abilities of Large Language Models', authors: 'Jiayi Gui, Yiming Liu, Jiale Cheng, Xiaotao Gu, Xiao Liu, Hongning Wang, Yuxiao Dong, Jie Tang, Minlie Huang.', venue: "ACL' 25 Findings", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.findings-acl.77.pdf', code_url: null, sort_order: 17 },
  { title: 'TableLLM: Enabling Tabular Data Manipulation by LLMs in Real Office Usage Scenarios', authors: 'Xiaokang Zhang, Sijia Luo, Bohan Zhang, Zeyao Ma, Jing Zhang, Yang Li, Guanlin Li, Zijun Yao, Kangli Xu, Jinchang Zhou, Daniel Zhang-Li, Jifan Yu, Shu Zhao, Juanzi Li, Jie Tang.', venue: "ACL' 25 Findings", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.findings-acl.538/', code_url: null, sort_order: 18 },
  { title: 'HPSS: Heuristic Prompting Strategy Search for LLM Evaluators', authors: 'Bosi Wen, Pei Ke, Yufei Sun, Cunxiang Wang, Xiaotao Gu, Jinfeng Zhou, Jie Tang, Hongning Wang, Minlie Huang.', venue: "ACL' 25 Findings", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://aclanthology.org/2025.findings-acl.1282.pdf', code_url: null, sort_order: 19 },
  { title: 'T1: Advancing Language Model Reasoning through Reinforcement Learning and Inference Scaling', authors: 'Zhenyu Hou, Xin Lv, Rui Lu, Jiajie Zhang, Yujiang Li, Zijun Yao, Juanzi Li, Jie Tang, Yuxiao Dong.', venue: "ICML' 2025", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://icml.cc/virtual/2025/poster/43762', code_url: null, sort_order: 20 },
  { title: 'A Stronger Mixture of Low-Rank Experts for Fine-Tuning Foundation Models', authors: 'Mengyang Sun, Yihao Wang, Tao Feng, Dan Zhang, Yifan Zhu, and Jie Tang.', venue: "ICML' 2025", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://icml.cc/virtual/2025/poster/43508', code_url: null, sort_order: 21 },
  { title: 'ZeroFlow: Overcoming Catastrophic Forgetting is Easier than You Think', authors: 'Tao Feng, Wei Li, DiDi Zhu, Hangjie Yuan, Wendi Zheng, Dan Zhang, Jie Tang.', venue: "ICML' 2025", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://icml.cc/virtual/2025/poster/44360', code_url: null, sort_order: 22 },
  { title: 'VisualAgentBench: Towards Large Multimodal Models as Visual Foundation Agents', authors: 'Xiao Liu, Tianjie Zhang, Yu Gu, Iat Long Iong, Yifan Xu, Xixuan Song, Shudan Zhang, Hanyu Lai, Xinyi Liu, Hanlin Zhao, Jiadai Sun, Xinyue Yang, Yu Yang, Zehan Qi, Shuntian Yao, Xueqiao Sun, Siyi Cheng, Qinkai Zheng, Hao Yu, Hanchen Zhang, Wenyi Hong, Ming Ding, Lihang Pan, Xiaotao Gu, Aohan Zeng, Zhengxiao Du, Chan Hee Song, Yu Su, Yuxiao Dong, Jie Tang.', venue: "ICLR' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://iclr.cc/virtual/2025/poster/31108', code_url: null, sort_order: 23 },
  { title: 'LongWriter: Unleashing 10,000+ Word Generation from Long Context LLMs', authors: 'Yushi Bai, Jiajie Zhang, Xin Lv, Linzhi Zheng, Siqi Zhu, Lei Hou, Yuxiao Dong, Jie Tang, Juanzi Li.', venue: "ICLR' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://proceedings.iclr.cc/paper_files/paper/2025/file/59f278de1619bdb6b53fd04e8e0976e0-Paper-Conference.pdf', code_url: 'https://github.com/THUDM/LongWriter', sort_order: 24 },
  { title: 'WebRL: Training LLM Web Agents via Self-Evolving Online Curriculum Reinforcement Learning', authors: 'Zehan Qi, Xiao Liu, Iat Long Iong, Hanyu Lai, Xueqiao Sun, Wenyi Zhao, Yu Yang, Xinyue Yang, Jiadai Sun, Shuntian Yao, Tianjie Zhang, Wei Xu, Jie Tang, Yuxiao Dong.', venue: "ICLR' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://proceedings.iclr.cc/paper_files/paper/2025/file/c66e1fcc9691aae706250638f36f681b-Paper-Conference.pdf', code_url: null, sort_order: 25 },
  { title: 'CogVideoX: Text-to-Video Diffusion Models with An Expert Transformer', authors: 'Zhuoyi Yang, Jiayan Teng, Wendi Zheng, Ming Ding, Shiyu Huang, Jiazheng Xu, Yuanming Yang, Wenyi Hong, Xiaohan Zhang, Guanyu Feng, Da Yin, Yuxuan Zhang, Weihan Wang, Yean Cheng, Bin Xu, Xiaotao Gu, Yuxiao Dong, Jie Tang.', venue: "ICLR' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://iclr.cc/virtual/2025/poster/29998', code_url: null, sort_order: 26 },
  { title: 'Scaling Speech-Text Pre-training with Synthetic Interleaved Data', authors: 'Aohan Zeng, Zhengxiao Du, Mingdao Liu, Lei Zhang, Shengmin Jiang, Yuxiao Dong, Jie Tang.', venue: "ICLR' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://iclr.cc/virtual/2025/poster/32109', code_url: null, sort_order: 27 },
  { title: 'Small Language Model Makes an Effective Long Text Extractor', authors: 'Yelin Chen, Fanjin Zhang, Jie Tang.', venue: "AAAI' 25", year: 2025, category: 'conference', venue_tier: 'top-tier', pdf_url: 'https://ojs.aaai.org/index.php/AAAI/article/view/34532/36687', code_url: null, sort_order: 28 },

  // Selected Prior Work
  { title: 'GLM-130B: An Open Bilingual Pre-trained Model', authors: 'Aohan Zeng, Xiao Liu, Zhengxiao Du, Zihan Wang, Hanyu Lai, Ming Ding, Zhuoyi Yang, Yifan Xu, Wendi Zheng, Xiao Xia, Weng Lam Tam, Zixuan Ma, Yufei Xue, Jidong Zhai, Wenguang Chen, Zhiyuan Liu, Peng Zhang, Yuxiao Dong, Jie Tang.', venue: 'ICLR 2023', year: 2023, category: 'prior', venue_tier: 'top-tier', pdf_url: 'https://arxiv.org/pdf/2210.02414', code_url: 'https://github.com/zai-org/GLM-130B', sort_order: 1 },
  { title: 'ArnetMiner: Extraction and Mining of Academic Social Networks', authors: 'Jie Tang, Jing Zhang, Limin Yao, Juanzi Li, Li Zhang, Zhong Su.', venue: 'KDD 2008', year: 2008, category: 'prior', venue_tier: 'top-tier', pdf_url: 'https://dl.acm.org/doi/epdf/10.1145/1401890.1402008', code_url: null, sort_order: 2 },
];

async function main() {
  const db = await init();

  // Run schema
  const schema = fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8');
  const statements = schema.split(';').filter(s => s.trim());
  for (const stmt of statements) {
    db.exec(stmt + ';');
  }

  // Seed admin
  const existing = db.prepare('SELECT id FROM admins WHERE username = ?').get(config.admin.defaultUsername);
  if (!existing) {
    const hash = bcrypt.hashSync(config.admin.defaultPassword, 10);
    db.prepare('INSERT INTO admins (username, password_hash) VALUES (?, ?)').run(config.admin.defaultUsername, hash);
    console.log(`Admin user "${config.admin.defaultUsername}" created.`);
  }

  // Seed people
  const peopleCount = db.prepare('SELECT COUNT(*) as cnt FROM people').get();
  if (peopleCount.cnt === 0) {
    for (const p of people) {
      db.prepare(
        `INSERT INTO people (name, title, role, photo, photo_position, link, supervisor, email, bio, year_start, year_end, sort_order, is_active)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)`
      ).run(
        p.name, p.title, p.role, p.photo, p.photo_position,
        p.link, p.supervisor, p.email, p.bio,
        p.year_start, p.year_end, p.sort_order
      );
    }
    console.log(`Seeded ${people.length} people.`);
  } else {
    console.log(`People table already has ${peopleCount.cnt} rows, skipping.`);
  }

  // Seed articles
  const articleCount = db.prepare('SELECT COUNT(*) as cnt FROM articles').get();
  if (articleCount.cnt === 0) {
    for (const a of articles) {
      db.prepare(
        `INSERT INTO articles (title, slug, excerpt, content, cover_image, category, type, is_published, published_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?)`
      ).run(a.title, a.slug, a.excerpt, a.content, a.cover_image, a.category, a.type, a.published_at);
    }
    console.log(`Seeded ${articles.length} articles.`);
  } else {
    console.log(`Articles table already has ${articleCount.cnt} rows, skipping.`);
  }

  // Seed events
  const eventCount = db.prepare('SELECT COUNT(*) as cnt FROM events').get();
  if (eventCount.cnt === 0) {
    for (const e of events) {
      db.prepare(
        `INSERT INTO events (title, description, speaker, location, event_date, event_type, is_upcoming)
         VALUES (?, ?, ?, ?, ?, ?, ?)`
      ).run(e.title, e.description, e.speaker, e.location, e.event_date, e.event_type, e.is_upcoming);
    }
    console.log(`Seeded ${events.length} events.`);
  } else {
    console.log(`Events table already has ${eventCount.cnt} rows, skipping.`);
  }

  // Seed recruitments
  const recruitCount = db.prepare('SELECT COUNT(*) as cnt FROM recruitments').get();
  if (recruitCount.cnt === 0) {
    const positions = [
      ['Postdoctoral Fellow: Quantization, Inference Infrastructure Optimization & GPU Optimization', 'postdoc', 'Research on quantization techniques, inference infrastructure optimization, and GPU kernel development for large language models.', 'tangjie@tsinghua.edu.cn', 1],
      ['Postdoctoral Fellow: AI for Science & Academic Big Data', 'postdoc', 'Research on AI for scientific discovery and large-scale academic knowledge graph construction.', 'tangjie@tsinghua.edu.cn', 1],
    ];
    for (const p of positions) {
      db.prepare('INSERT INTO recruitments (title, position_type, description, contact_email, is_featured) VALUES (?, ?, ?, ?, ?)').run(...p);
    }
    console.log('Recruitments seeded.');
  }

  // Seed publications
  const pubCount = db.prepare('SELECT COUNT(*) as cnt FROM publications').get();
  if (pubCount.cnt === 0) {
    for (const p of publications) {
      db.prepare(
        `INSERT INTO publications (title, authors, venue, year, category, venue_tier, pdf_url, code_url, sort_order, is_active)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 1)`
      ).run(
        p.title, p.authors, p.venue, p.year, p.category, p.venue_tier,
        p.pdf_url, p.code_url, p.sort_order
      );
    }
    console.log(`Seeded ${publications.length} publications.`);
  } else {
    console.log(`Publications table already has ${pubCount.cnt} rows, skipping.`);
  }

  console.log('Database seeded successfully at:', config.dbPath);
}

main().catch(err => {
  console.error('Seed failed:', err);
  process.exit(1);
});
